apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hotstar-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: hotstar
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics