apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      # 🔹 Application container
      - name: hotstar-container
        image: monikasapawar/hotstar
        ports:
        - containerPort: 3000

      # 🔹 Metrics Exporter container (Prometheus will scrape from here)
      - name: metrics-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
  labels:
    app: hotstar
spec:
  type: LoadBalancer
  selector:
    app: hotstar
  ports:
  - name: http           # <-- required
    port: 80
                                  